image: python:3.8

stages:
    - lint
    - test
    - build
    - publish
    - release

before_script:
    - pip install --user poetry

lint:
    stage: lint
    script:
        - make lint-docker
        - python -m pip install --upgrade pre-commit
        - make lint

test:
    needs:
        - lint
    stage: test
    script:
        - make test

build:
    stage: build
    needs:
        - test
    script:
        - make build

publish:
    stage: publish
    only:
        - main
    script:
        - mkdir -p ~/.pip/
        - echo -e "[global]\nindex-url = $PIP_REGISTRY_URL" > ~/.pip/pip.conf
        - make build
        - twine upload --repository-url $PIP_REGISTRY_URL dist/*

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    only:
        - main
    # TODO: release job
    script:
        - echo 'Releasing application'