image: python:3.10.4

stages:
    - lint
    - security
    - test
    - build
    - publish
    - release

before_script:
    - pip install --user poetry
    - poetry install

lint:
    stage: lint
    script:
        - make lint

license-check:
    stage: security
    needs:
        - lint
    script:
        - make license-check

test:
    stage: test
    needs:
        - scan
    script:
        - make test

build:
    stage: build
    needs:
        - test
    script:
        - make build

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    only:
        - main
    # TODO: release job
    script:
        - echo 'Releasing application'
